kind: Template
apiVersion: v1
metadata:
  name: httpd-example
labels:
  role: web
message: "You chose to deploy docker.io/centos/httpd"
objects:
  - apiVersion: "v1"
    kind: "Pod"
    metadata:
      name: "mywebserverpod"
      labels: 
        name: "webserver"
    spec:
      containers:
        - name: "webserver"
          image: "docker.io/centos/httpd"
          ports:
            - name: "web"
              containerPort: 8080
