kind: Template
apiVersion: v1
metadata:
  name: httpd-example
labels:
  role: web
message: You chose to deploy ${WEB_SERVER}
objects:
  - kind: Pod
    apiVersion: "v1"
    metadata:
      name: "mywebserverpod"
      labels: 
        name: "webserver"
    spec:
      containers:
        - name: "webserver"
          image: ${WEB_SERVER}
          ports:
            - name: "web"
              containerPort: 80
          volumeMounts:
            - name: volume-webroot
              mountPath: "/var/www/html"
      volumes:
        - name: volume-webroot
          persistentVolumeClaim:
            claimName: pvc-web
      PersistentVolumeClaim:
        - metadata:
            name: "pvc-web"
          spec:
            accessModes:
              - "ReadWriteMany"
            resources:
              requests:
                storage: 1Gi
parameters:
  - name: WEB_SERVER
    displayName: Web Server
    description: Web server image to use
    value: centos/httpd-24-centos7
